Repository jdi-testing/jdi-light, pull requests merged in 2019-12, with the labels that each got.

#1455 1407 bootstap list group test fix
  jdi-light-bootstrap-tests/src/test/java/io/github/epam/bootstrap/tests/composite/section/listGroup/DisabledItemsTests.java
Labels: bootstrap

#1463 1383 - Alert class updates
  jdi-light-bootstrap/src/main/java/com/epam/jdi/light/ui/bootstrap/elements/common/Alert.java
Labels: bootstrap

#1468 1382 - Button Group Classes updated
  jdi-light-bootstrap-tests/src/main/java/io/github/com/pages/BootstrapPage.java
  jdi-light-bootstrap-tests/src/main/java/io/github/com/sections/buttongroup/ButtonGroupBasic.java
  jdi-light-bootstrap-tests/src/main/java/io/github/com/sections/buttongroup/ButtonGroupBasicExample.java
  jdi-light-bootstrap-tests/src/main/java/io/github/com/sections/buttongroup/ButtonGroupNesting.java
  jdi-light-bootstrap-tests/src/main/java/io/github/com/sections/buttongroup/ButtonGroupSizing.java
  jdi-light-bootstrap-tests/src/main/java/io/github/com/sections/buttongroup/ButtonGroupToolbar.java
  jdi-light-bootstrap-tests/src/main/java/io/github/com/sections/buttongroup/ButtonGroupVerticalVariation.java
  jdi-light-bootstrap-tests/src/main/java/io/github/com/sections/inputgroup/InputGroupButtonWithDropdown.java
  jdi-light-bootstrap-tests/src/test/java/io/github/epam/bootstrap/tests/composite/section/buttonGroup/BasicTests.java
  jdi-light-bootstrap-tests/src/test/java/io/github/epam/bootstrap/tests/composite/section/buttonGroup/ToolbarTests.java
  jdi-light-bootstrap-tests/src/test/java/io/github/epam/bootstrap/tests/composite/section/inputgroup/InputGroupButtonWithDropdownTests.java
  jdi-light-bootstrap/src/main/java/com/epam/jdi/light/ui/bootstrap/elements/complex/ButtonGroup.java
Labels: bootstrap

#1473 1339 fix
  jdi-light/src/main/java/com/epam/jdi/light/common/Property.java
  jdi-light/src/test/java/io/github/epam/properties/DriversFolderTests.java
Labels: param

#1457 1408 bootstap paginator fix test
  jdi-light-bootstrap-tests/src/test/java/io/github/epam/bootstrap/tests/composite/section/pagination/AlignTests.java
  jdi-light-bootstrap-tests/src/test/java/io/github/epam/bootstrap/tests/composite/section/pagination/IconsTests.java
  jdi-light-bootstrap-tests/src/test/java/io/github/epam/bootstrap/tests/composite/section/pagination/OverviewTests.java
  jdi-light-bootstrap-tests/src/test/java/io/github/epam/bootstrap/tests/composite/section/pagination/StatesTests.java
Labels: bootstrap

#1460 #1399 - Review all tests for the element and methods for that element…
  jdi-light-bootstrap-tests/src/main/java/io/github/com/pages/BootstrapPage.java
  jdi-light-bootstrap-tests/src/test/java/io/github/epam/bootstrap/tests/complex/MultipleProgressBarsTests.java
  jdi-light-bootstrap/src/main/java/com/epam/jdi/light/ui/bootstrap/elements/complex/MultipleProgressBars.java
Labels: bootstrap

#1483 1384_review_test_for_badge
  jdi-light-bootstrap-tests/src/main/java/io/github/com/pages/BootstrapPage.java
  jdi-light-bootstrap-tests/src/test/java/io/github/epam/bootstrap/tests/common/BadgeTests.java
  jdi-light-bootstrap/src/main/java/com/epam/jdi/light/ui/bootstrap/elements/common/Badge.java
  jdi-light-bootstrap/src/main/java/com/epam/jdi/light/ui/bootstrap/elements/complex/ButtonWithBadge.java
Labels: bootstrap

#1482 1415 fix codacy
  jdi-light/src/main/java/com/epam/jdi/light/actions/ActionOverrideUtils.java
  jdi-light/src/main/java/com/epam/jdi/light/actions/ActionProcessor.java
  jdi-light/src/main/java/com/epam/jdi/light/elements/init/UIFactory.java
  jdi-performance/src/test/java/org/mytests/tests/PerfStatistic.java
Labels: codacy issues

#1484 #1249 - allure screenshoots
  jdi-light-examples/src/test/java/io/github/epam/testng/TestNGListener.java
  jdi-light-examples/src/test/java/io/github/epam/tests/allurereport/AllureScreenshotTests.java
  jdi-light-examples/src/test/resources/allureScreenshot.xml
  jdi-light/src/main/java/com/epam/jdi/light/logger/ILogger.java
  jdi-light/src/main/java/com/epam/jdi/light/logger/JDILogger.java
  jdi-light/src/main/java/com/epam/jdi/light/settings/WebSettings.java
Labels: bootstrap

#1470 L 1261 fields declared at the top of the class
  jdi-light/src/main/java/com/epam/jdi/light/elements/complex/ListBase.java
  jdi-light/src/main/java/com/epam/jdi/light/elements/init/PageFactory.java
Labels: bootstrap

#1453 1338. timeout.wait.page and domain properties
  jdi-light/src/main/java/com/epam/jdi/light/common/Property.java
  jdi-light/src/main/java/com/epam/jdi/light/settings/WebSettings.java
  jdi-light/src/test/java/io/github/epam/properties/DomainTests.java
  jdi-light/src/test/java/io/github/epam/properties/TimeoutWaitPageTests.java
Labels: bootstrap, param

#1499 moved class ProgressBarsListTests
  jdi-light-bootstrap-tests/src/test/java/io/github/epam/bootstrap/tests/common/progress/ProgressBarsListTests.java
Labels: bootstrap

#1538 1504 test parameters screenshot strgy fix
  jdi-light/src/main/java/com/epam/jdi/light/common/Property.java
Labels: param

#1502 1448 creation abstract toast class
  jdi-light-bootstrap/src/main/java/com/epam/jdi/light/ui/bootstrap/elements/composite/Toast.java
Labels: bootstrap

#875 Fix travis runs
  .travis.yml
  jdi-light/src/main/java/com/epam/jdi/light/driver/get/DriverData.java
  jdi-light/src/main/java/com/epam/jdi/light/settings/WebSettings.java
  reports.sh
Labels: travis

#1549 #1451 - research logs
  jdi-light-bootstrap-tests/src/test/java/io/github/epam/testng/TestNGListener.java
  jdi-light-bootstrap/src/main/java/com/epam/jdi/light/ui/bootstrap/actions/BSActions.java
  jdi-light-examples/src/test/java/io/github/epam/testng/TestNGListener.java
  jdi-light-html/src/main/java/com/epam/jdi/light/ui/html/actions/HtmlActions.java
  jdi-light/src/main/java/com/epam/jdi/light/actions/ActionHelper.java
  jdi-light/src/main/java/com/epam/jdi/light/actions/ActionProcessor.java
  jdi-light/src/main/java/com/epam/jdi/light/driver/ScreenshotMaker.java
  jdi-light/src/main/java/com/epam/jdi/light/logger/AllureLoggerHelper.java
  jdi-light/src/main/java/com/epam/jdi/light/logger/ILogger.java
  jdi-light/src/main/java/com/epam/jdi/light/logger/JDILogger.java
  jdi-light/src/main/java/com/epam/jdi/light/settings/WebSettings.java
Labels: enhancement

#1565 1313 Fix maven warnings during build
  .travis.yml
  jdi-light-bdd-no-po-tests/pom.xml
  jdi-light-bdd-tests/pom.xml
  jdi-light-bdd/pom.xml
  jdi-light-bootstrap-tests/pom.xml
  jdi-light-bootstrap/pom.xml
  jdi-light-examples/pom.xml
  jdi-light-html-tests/pom.xml
  jdi-light-html/pom.xml
  jdi-light/pom.xml
  jdi-performance/pom.xml
  maven-version-rules.xml
  pom.xml
Labels: travis

#1547 L 1475
  jdi-light/src/main/java/com/epam/jdi/light/settings/WebSettings.java
Labels: bootstrap

#1576 1514 Checkbox example tests
  jdi-light-html-tests/src/test/java/io/github/epam/example/common/CheckboxExampleTests.java
Labels: htmlExample

#1580 add Link Assert examples
  jdi-light-html-tests/src/test/java/io/github/epam/example/common/LinkExampleTests.java
Labels: htmlExample

#1582 1518 add link click test example
  jdi-light-html-tests/src/test/java/io/github/epam/example/common/LinkExampleTests.java
Labels: htmlExample

#1583 1522 html example text
  jdi-light-html-tests/src/test/java/io/github/epam/example/common/TextExampleTests.java
Labels: htmlExample

#1586 1516 html example file input
  .travis.yml
  jdi-light-html-tests/src/test/java/io/github/epam/example/common/FileInputExampleTests.java
Labels: htmlExample

#1587 1524 Text Area Examples
  jdi-light-html-tests/src/test/java/io/github/epam/example/common/ImageExampleTests.java
  jdi-light-html-tests/src/test/java/io/github/epam/example/common/TextAreaExampleTests.java
Labels: htmlExample

#1591 1513 html example colorpicker
  jdi-light-html-tests/src/test/java/io/github/epam/example/common/ColorPickerExample.java
Labels: htmlExample

#1596 1519 html example Menu
  jdi-light-html-tests/src/test/java/io/github/epam/example/complex/MenuExampleTests.java
Labels: htmlExample

#1598 1521 range example
  jdi-light-html-tests/src/test/java/io/github/epam/example/common/ButtonExampleTests.java
  jdi-light-html-tests/src/test/java/io/github/epam/example/common/CheckboxExampleTests.java
  jdi-light-html-tests/src/test/java/io/github/epam/example/common/RangeExampleTests.java
Labels: htmlExample

#1570 1569 cherry pick travis commits
  .travis.yml
  jdi-light-html-tests/src/test/java/io/github/epam/TestsInit.java
  jdi-light-html-tests/src/test/resources/general.xml
  jdi-light/src/main/java/com/epam/jdi/light/driver/get/DriverData.java
  jdi-light/src/main/java/com/epam/jdi/light/settings/WebSettings.java
  reports.sh
Labels: travis

#1602 1520 Progress html example
  jdi-light-html-tests/src/test/java/io/github/epam/example/common/ProgressExampleTests.java
  jdi-light-html-tests/src/test/java/io/github/epam/example/complex/MenuExampleTests.java
Labels: htmlExample

#1605 1525 Title html example
  jdi-light-html-tests/src/test/java/io/github/epam/example/common/TitleExampleTests.java
Labels: htmlExample

#1609 1531 DataList html example
  jdi-light-html-tests/src/test/java/io/github/epam/example/complex/DataListExampleTests.java
Labels: htmlExample

#1606 1523 textfield html example
  jdi-light-html-tests/src/test/java/io/github/epam/example/common/TextFieldExampleTests.java
  jdi-light-html-tests/src/test/java/io/github/epam/html/tests/elements/common/TextFieldTests.java
Labels: htmlExample

#1616 1529 dropdown
  jdi-light-html-tests/src/test/java/io/github/epam/example/complex/DropdownExampleTests.java
Labels: htmlExample

#1617 1533 html example MultiSelector
  jdi-light-html-tests/src/test/java/io/github/epam/example/complex/MultiSelectorExampleTests.java
Labels: htmlExample
