Repository jdi-testing/jdi-light, pull requests merged in 2020-02, with the labels that each got.

#1706 JDI working with Appium now
  jdi-light-html-tests/pom.xml
  jdi-light-html-tests/src/main/java/io/github/com/StaticSite.java
  jdi-light-html-tests/src/main/java/io/github/com/pages/HomePage.java
  jdi-light-html-tests/src/main/java/io/github/com/pages/HtmlElementsPage.java
  jdi-light-html-tests/src/test/java/io/github/epam/CustomDriverTestsInit.java
  jdi-light-html-tests/src/test/java/io/github/epam/TestsInit.java
  jdi-light-html-tests/src/test/java/io/github/epam/html/tests/elements/common/DateTests.java
  jdi-light-mobile-examples/src/main/java/io/github/com/StaticSite.java
  jdi-light-mobile/pom.xml
  jdi-light-mobile/src/main/java/com/epam/jdi/mobile/driver/WebDriverFactory.java
  jdi-light-mobile/src/main/java/com/epam/jdi/mobile/driver/get/DriverData.java
  jdi-light-mobile/src/main/java/com/epam/jdi/mobile/driver/get/DriverInfo.java
  jdi-light-mobile/src/main/java/com/epam/jdi/mobile/driver/get/DriverInfos.java
  jdi-light-mobile/src/main/java/com/epam/jdi/mobile/driver/get/DriverTypes.java
  jdi-light-mobile/src/main/java/com/epam/jdi/mobile/driver/get/MobileDriver.java
  jdi-light-mobile/src/main/java/com/epam/jdi/mobile/elements/init/PageFactory.java
  jdi-light-mobile/src/main/java/com/epam/jdi/mobile/settings/WebSettings.java
  pom.xml
Labels: appium

#556 task 550 - implement screenshoting alerts on test failing
  jdi-light-html-tests/src/test/java/io/github/epam/testng/TestNGListener.java
  jdi-light/pom.xml
  jdi-light/src/main/java/com/epam/jdi/light/driver/ScreenshotMaker.java
Labels: 1.1

#1615 1532 html example check list
  jdi-light-html-tests/src/test/java/io/github/epam/example/complex/CheckListExampleTests.java
Labels: htmlExample
